"""Transaction processing pipeline — public API formerly on transaction_insight.core."""

from webapp.excel.export import write_excel
from webapp.excel.formatting import (
    autofit_workbook,
    format_baseline_worksheet,
    format_spending_insights_worksheet,
    format_transaction_worksheet,
    open_excel_workbook,
)
from webapp.excel.insights import (
    build_baseline_sheets,
    build_month_category_breakdown,
    build_monthly_expense_overview,
    write_baseline_sheet,
    write_spending_insights_sheet,
)
from webapp.llm.classify import (
    classify_all,
    classify_batch,
    classify_review_mask,
    classify_review_rows,
    extract_json_payload,
)
from webapp.llm.client import (
    BATCH_SIZE,
    CLASSIFICATION_BATCH_SIZE,
    DESCRIPTION_BATCH_SIZE,
    LOCAL_BATCH_SIZE,
    LOCAL_PROVIDERS,
    LM_STUDIO_BASE_URL,
    LM_STUDIO_MODEL,
    OLLAMA_BASE_URL,
    OLLAMA_MODEL,
    OPENAI_MODEL,
    REQUEST_TIMEOUT,
    create_client,
    json_for_prompt,
    resolve_batch_sizes,
    resolve_provider_config,
)
from webapp.llm.descriptions import (
    build_description_lookup_map,
    description_source_key,
    fill_generated_descriptions,
    generate_descriptions_batch,
    merge_description_lookup,
)
from webapp.llm.validation import generated_description_plausible
from webapp.llm.prompts import (
    BUSINESS_RULE_PROMPT,
    CLASSIFICATION_PROMPT,
    CUSTOM_RULE_COMPILER_PROMPT,
    DESCRIPTION_PROMPT,
)
from webapp.processing.business_rules import (
    apply_business_rules_to_df,
    business_category_rule_keys,
    business_rows_needing_rules,
    enrich_business_lookup_rules,
    mark_business_from_category_rules,
    merge_business_category_rules,
    print_business_tagging_summary,
)
from webapp.processing.cadence import (
    analyze_merchant_cadence_profiles,
    apply_detected_expense_cadence,
    apply_expense_cadence_lookup,
    build_analytics_ledger,
    build_cadence_review_df,
    empty_expense_cadence_rules_sheet,
    finalize_expense_cadence_defaults,
    init_expense_cadence_columns,
    merge_expense_cadence_rules,
    normalize_expense_cadence_rules_sheet,
)
from webapp.processing.constants import *
from webapp.processing.custom_rules import (
    apply_custom_rules,
    compile_custom_rule_text,
    compile_custom_rules_sheet,
    empty_custom_rules_sheet,
    load_active_custom_rules,
    normalize_custom_rules_sheet,
)
from webapp.processing.custom_rules import _custom_rule_match_mask
from webapp.processing.flow import (
    budget_tier_from_category,
    cost_type_from_category,
    flow_type_from_row,
    is_paycheck_row,
)
from webapp.processing.lookups import (
    apply_lookup_rules,
    apply_merchant_category_lookup,
    build_merchant_category_map,
    default_lookup_path,
    load_lookup_workbook,
    update_lookup_workbook,
)
from webapp.processing.parse import (
    assign_transaction_ids,
    drop_rows_with_invalid_dates,
    ensure_merchant_key_column,
    heuristic_generated_description,
    load_csv,
    merchant_key,
    parse_amount,
    parse_transaction_dates,
    prepare_transaction_export_df,
    sort_expenses_for_export,
    transaction_fingerprint,
)
from webapp.processing.timer import PhaseTimer, format_duration

__all__ = [
    "BATCH_SIZE",
    "CLASSIFICATION_BATCH_SIZE",
    "DESCRIPTION_BATCH_SIZE",
    "LOCAL_BATCH_SIZE",
    "LOCAL_PROVIDERS",
    "LM_STUDIO_BASE_URL",
    "LM_STUDIO_MODEL",
    "OLLAMA_BASE_URL",
    "OLLAMA_MODEL",
    "OPENAI_MODEL",
    "REQUEST_TIMEOUT",
    "PhaseTimer",
    "apply_business_rules_to_df",
    "apply_custom_rules",
    "apply_detected_expense_cadence",
    "apply_expense_cadence_lookup",
    "apply_lookup_rules",
    "apply_merchant_category_lookup",
    "assign_transaction_ids",
    "autofit_workbook",
    "analyze_merchant_cadence_profiles",
    "build_analytics_ledger",
    "build_baseline_sheets",
    "build_cadence_review_df",
    "build_description_lookup_map",
    "build_merchant_category_map",
    "build_month_category_breakdown",
    "build_monthly_expense_overview",
    "budget_tier_from_category",
    "business_category_rule_keys",
    "business_rows_needing_rules",
    "classify_all",
    "classify_batch",
    "classify_review_mask",
    "classify_review_rows",
    "compile_custom_rule_text",
    "compile_custom_rules_sheet",
    "cost_type_from_category",
    "create_client",
    "default_lookup_path",
    "drop_rows_with_invalid_dates",
    "empty_custom_rules_sheet",
    "empty_expense_cadence_rules_sheet",
    "enrich_business_lookup_rules",
    "ensure_merchant_key_column",
    "extract_json_payload",
    "fill_generated_descriptions",
    "finalize_expense_cadence_defaults",
    "flow_type_from_row",
    "format_baseline_worksheet",
    "format_duration",
    "format_spending_insights_worksheet",
    "format_transaction_worksheet",
    "generate_descriptions_batch",
    "generated_description_plausible",
    "heuristic_generated_description",
    "init_expense_cadence_columns",
    "is_paycheck_row",
    "json_for_prompt",
    "load_active_custom_rules",
    "load_csv",
    "load_lookup_workbook",
    "mark_business_from_category_rules",
    "merge_business_category_rules",
    "merge_description_lookup",
    "merge_expense_cadence_rules",
    "merchant_key",
    "normalize_custom_rules_sheet",
    "normalize_expense_cadence_rules_sheet",
    "open_excel_workbook",
    "parse_amount",
    "parse_transaction_dates",
    "prepare_transaction_export_df",
    "print_business_tagging_summary",
    "resolve_batch_sizes",
    "resolve_provider_config",
    "sort_expenses_for_export",
    "transaction_fingerprint",
    "update_lookup_workbook",
    "write_baseline_sheet",
    "write_excel",
    "write_spending_insights_sheet",
    "_custom_rule_match_mask",
]
